# Generated by Django 5.2.8 on 2025-11-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variataion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variataion',
            new_name='Variation',
        ),
    ]
